### ISSUE TITLE
I'm in. <Join in progress, please wait.>

### ISSUE THREAD

**Issue by CaptainTimothy** [smilonely/I-dont-wanna-read-it#2]
# I'm in.
###### I'm in.
> I'm in.
>> I'm in.
>>> I'm in.
***
>>>> I'm in.
>>>>> I'm in.
>>>>>> I'm in.

- [ ] ~~I've read all the things above and I agree to take part in this project.~~

<p  align='right'><a href=https://github.com/smilonely/I-dont-wanna-read-it><img src='https://i.loli.net/2019/04/22/5cbca2576699e.png'/></a>&nbsp;&nbsp;</p>

<p align='right'>
<a href=https://github.com/smilonely/I-dont-wanna-read-it>
OKAY, I‘M IN.
</a>
</p>

**Comment by shawshuai** [comment]
23333333
The button！

**Comment by smilonely** [comment]
Pretty coo00OO00ooOOl

**Comment by CaptainTimothy** [comment]
# I'm in.
## I'm in.
### I'm in.
#### I'm in.
##### I'm in.
###### I'm in.
> I'm in.
>> I'm in.
>>> I'm in.
***
>>>> I'm in.
>>>>> I'm in.
>>>>>> I'm in.

- [ ] ~~I've read all the things above and I agree to take part in this project.~~

<p  align='right'><a href=https://github.com/smilonely/I-dont-wanna-read-it><img src='https://i.loli.net/2019/04/22/5cbca2576699e.png'/></a>&nbsp;&nbsp;</p>


<p align='right'>
<a href=https://github.com/smilonely/I-dont-wanna-read-it>
OKAY, I‘M IN.
</a>
</p>
